# This workflow installs the latest version of Copilot CLI. On push events
# to the $default-branch branch, a deploy will be executed.

name: "Copilot Deploy"

on:
  push:
    branches:
      - $default-branch

jobs:
  copilot:
    name: "Copilot Deploy"
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      # Install the latest version of Copilot CLI
      - name: Setup Copilot
        uses: additionwealth/setup-aws-copilot@v1

      # On push to $default-branch, deploy
      - name: Copilot Deploy
        if: github.ref == 'refs/heads/$default-branch' && github.event_name == 'push'
        run: copilot svc deploy
